# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guide.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(728, 490)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.guide_image = QtWidgets.QFrame(Dialog)
        self.guide_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.guide_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.guide_image.setObjectName("guide_image")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.guide_image)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo = QtWidgets.QPushButton(self.guide_image)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.logo.setFont(font)
        self.logo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logo.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(60, 60, 60);\n"
"}")
        self.logo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("variable/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo.setIcon(icon)
        self.logo.setIconSize(QtCore.QSize(70, 70))
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.logo)
        self.label_4 = QtWidgets.QLabel(self.guide_image)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(94, 94, 94);")
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.soft_brief = QtWidgets.QLabel(self.guide_image)
        self.soft_brief.setMinimumSize(QtCore.QSize(0, 120))
        self.soft_brief.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.soft_brief.setFont(font)
        self.soft_brief.setStyleSheet("color: rgb(80, 80, 80);\n"
"background-color: rgba(207, 207, 207, 80);")
        self.soft_brief.setScaledContents(False)
        self.soft_brief.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.soft_brief.setWordWrap(True)
        self.soft_brief.setIndent(-1)
        self.soft_brief.setObjectName("soft_brief")
        self.verticalLayout_2.addWidget(self.soft_brief)
        self.pushButton = QtWidgets.QPushButton(self.guide_image)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(94, 94, 94);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("variable/icons/xylogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.guide_image)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(80, 80, 80);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.create_project = QtWidgets.QPushButton(self.frame)
        self.create_project.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.create_project.setFont(font)
        self.create_project.setStyleSheet("QPushButton{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(0, 172, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    height:28px;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(0, 134, 67);\n"
"    color: rgb(255, 255, 255);\n"
"    height:28px;\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(0, 172, 83);\n"
"    color: rgb(255, 255, 255);\n"
"    height:28px;\n"
"}")
        self.create_project.setObjectName("create_project")
        self.verticalLayout.addWidget(self.create_project)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.open_project = QtWidgets.QPushButton(self.frame_3)
        self.open_project.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.open_project.setFont(font)
        self.open_project.setStyleSheet("QPushButton{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(125, 125, 125);\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    height:28px;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(111, 111, 111);\n"
"    color: rgb(255, 255, 255);\n"
"    height:28px;\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(86, 86, 86);\n"
"    color: rgb(255, 255, 255);\n"
"    height:28px;\n"
"}")
        self.open_project.setObjectName("open_project")
        self.horizontalLayout_3.addWidget(self.open_project)
        self.import_image = QtWidgets.QPushButton(self.frame_3)
        self.import_image.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.import_image.setFont(font)
        self.import_image.setStyleSheet("QPushButton{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(125, 125, 125);\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    height:28px;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(111, 111, 111);\n"
"    color: rgb(255, 255, 255);\n"
"    height:28px;\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(86, 86, 86);\n"
"    color: rgb(255, 255, 255);\n"
"    height:28px;\n"
"}")
        self.import_image.setObjectName("import_image")
        self.horizontalLayout_3.addWidget(self.import_image)
        self.import_video = QtWidgets.QPushButton(self.frame_3)
        self.import_video.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.import_video.setFont(font)
        self.import_video.setStyleSheet("QPushButton{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(125, 125, 125);\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    height:28px;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(111, 111, 111);\n"
"    color: rgb(255, 255, 255);\n"
"    height:28px;\n"
"}\n"
"QPushButton:pressed{\n"
"    font: 9pt \"微软雅黑\";\n"
"    background-color: rgb(86, 86, 86);\n"
"    color: rgb(255, 255, 255);\n"
"    height:28px;\n"
"}")
        self.import_video.setObjectName("import_video")
        self.horizontalLayout_3.addWidget(self.import_video)
        self.verticalLayout.addWidget(self.frame_3)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(80, 80, 80);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.recently = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.recently.setFont(font)
        self.recently.setStyleSheet("QListWidget{\n"
"border:none;\n"
"}")
        self.recently.setObjectName("recently")
        self.verticalLayout.addWidget(self.recently)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "——多模型对象检测系统——"))
        self.soft_brief.setText(_translate("Dialog", "      机器视觉是人工智能正在快速发展的一个分支。简单说来，机器视觉就是用机器代替人眼来做测量和判断。机器视觉系统是通过机器视觉产品(即图像摄取装置，分CMOS和CCD两种)将被摄取目标转换成图像信号，传送给专用的图像处理系统，得到被摄目标的形态信息，根据像素分布和亮度、颜色等信息，转变成数字化信号;图像系统对这些信号进行各种运算来抽取目标的特征，进而根据判别的结果来控制现场的设备动作。"))
        self.pushButton.setText(_translate("Dialog", "江小鱼科创工作室 Copyright 2023"))
        self.label_3.setText(_translate("Dialog", "项目与文件"))
        self.create_project.setText(_translate("Dialog", "创建新项目"))
        self.open_project.setText(_translate("Dialog", "打开项目"))
        self.import_image.setText(_translate("Dialog", "导入图像"))
        self.import_video.setText(_translate("Dialog", "导入视频"))
        self.label_2.setText(_translate("Dialog", "最近项目"))
