# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_image = QtWidgets.QLabel(self.centralwidget)
        self.start_image.setGeometry(QtCore.QRect(380, 20, 301, 381))
        self.start_image.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.start_image.setText("")
        self.start_image.setObjectName("start_image")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 60, 600, 340))
        self.widget.setStyleSheet("QWidget{\n"
"border:30px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(20, 20, 80, 80))
        self.logo.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(110, 20, 481, 51))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(66, 66, 66);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 310, 131, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(66, 66, 66);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(120, 70, 191, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(66, 66, 66);")
        self.label_3.setObjectName("label_3")
        self.running = QtWidgets.QLabel(self.widget)
        self.running.setGeometry(QtCore.QRect(40, 120, 161, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.running.setFont(font)
        self.running.setStyleSheet("color: rgb(66, 66, 66);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.running.setObjectName("running")
        self.info = QtWidgets.QLabel(self.widget)
        self.info.setGeometry(QtCore.QRect(170, 310, 431, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.info.setFont(font)
        self.info.setStyleSheet("color: rgb(66, 66, 66);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.info.setWordWrap(True)
        self.info.setObjectName("info")
        self.widget.raise_()
        self.start_image.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "---"))
        self.label_2.setText(_translate("MainWindow", "江小鱼科技(2023)"))
        self.label_3.setText(_translate("MainWindow", "智慧之眼，洞察世界 beta 2.23.2"))
        self.running.setText(_translate("MainWindow", "启动中.."))
        self.info.setText(_translate("MainWindow", "正在加载"))
